version: '3.9'
services:
    db:
        image: postgres:latest
        restart: always
        env_file:
            - ./.env

    app:
        restart: unless-stopped
        build:
            context: .
        command: python ./server.py
        ports:
            - 5000:5000
        depends_on:
            - db
        volumes:
            - .:/app
        env_file:
            - ./.env